### ISSUE TITLE
issues with running

### ISSUE THREAD

**Issue by Gav06** [snuckdev/discord-crasher-creator#1]
i followed the instructions in the readme,
and i get this error

```
Downloading ffmpeg-win.7z
Traceback (most recent call last):
  File "C:\Users\slies\Desktop\discord-crasher-creator-main\main.py", line 20, in <module>
    main()
  File "C:\Users\slies\Desktop\discord-crasher-creator-main\main.py", line 14, in main
    BinaryExtractor.extract_binaries()
  File "C:\Users\slies\Desktop\discord-crasher-creator-main\modules\binary_extractor.py", line 13, in extract_binaries
    Archive('bin/ffmpeg-win.7z').extractall('bin')
  File "C:\Users\slies\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyunpack\__init__.py", line 94, in extractall
    self.extractall_patool(directory, patool_path)
  File "C:\Users\slies\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyunpack\__init__.py", line 50, in extractall_patool
    raise ValueError("patool not found! Please install patool!")
ValueError: patool not found! Please install patool!
```

I ran `pip install patool` and ran it again, got the same message

any idea?

**Comment by snuckdev** [comment]
I forgot to add patool to the requirements.txt but after I install it it works. Can you send me your log after installing patool?

**Comment by Gav06** [comment]
ok sure

**Comment by snuckdev** [comment]
Closed because there is no response
